export * from './browser-tab.entity'
export * from './browser-view.entity'
export * from './navigation-bar-config.entity'
export * from './webview-option.entity'
export * from './browser-history.entity'